# Generated by Django 5.2.6 on 2025-12-26 04:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicCompetition",
            fields=[
                (
                    "first_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="一审意见"),
                ),
                (
                    "first_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="一审时间"
                    ),
                ),
                (
                    "second_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="二审意见"),
                ),
                (
                    "second_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="二审时间"
                    ),
                ),
                (
                    "third_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="三审意见"),
                ),
                (
                    "third_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="三审时间"
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "待一审"),
                            ("first_reviewing", "一审中"),
                            ("first_approved", "一审通过"),
                            ("first_rejected", "一审不通过"),
                            ("second_reviewing", "二审中"),
                            ("second_approved", "二审通过"),
                            ("second_rejected", "二审不通过"),
                            ("third_reviewing", "三审中"),
                            ("approved", "审核通过"),
                            ("rejected", "审核不通过"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("passed", "通过"), ("failed", "不通过")],
                        max_length=10,
                        null=True,
                        verbose_name="结果",
                    ),
                ),
                (
                    "estimated_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        verbose_name="预估分数",
                    ),
                ),
                (
                    "bonus_points",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=7, verbose_name="加分"
                    ),
                ),
                (
                    "college_opinion",
                    models.TextField(blank=True, null=True, verbose_name="学院意见"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "screenshot",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="academic_expertise/%Y/%m/%d/",
                        verbose_name="截图",
                    ),
                ),
                (
                    "user_explanation",
                    models.TextField(blank=True, null=True, verbose_name="用户说明"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition_level",
                    models.CharField(
                        choices=[
                            ("A+", "A+级"),
                            ("A", "A级"),
                            ("A-", "A-级"),
                            ("B+", "B+级"),
                            ("B", "B级"),
                        ],
                        max_length=5,
                        verbose_name="竞赛级别",
                    ),
                ),
                (
                    "competition_name",
                    models.CharField(
                        choices=[
                            ("math_modeling", "数学建模竞赛"),
                            ("programming", "程序设计竞赛"),
                            ("electronic_design", "电子设计竞赛"),
                            ("robotics", "机器人竞赛"),
                            ("business_plan", "创业计划大赛"),
                            ("other", "其他竞赛"),
                        ],
                        max_length=50,
                        verbose_name="竞赛名称",
                    ),
                ),
                (
                    "competition_specific_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="具体竞赛名称",
                    ),
                ),
                (
                    "award_level",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="获奖等级"
                    ),
                ),
            ],
            options={
                "verbose_name": "学业竞赛",
                "verbose_name_plural": "学业竞赛",
                "db_table": "academic_competition",
            },
        ),
        migrations.CreateModel(
            name="AcademicPaper",
            fields=[
                (
                    "first_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="一审意见"),
                ),
                (
                    "first_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="一审时间"
                    ),
                ),
                (
                    "second_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="二审意见"),
                ),
                (
                    "second_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="二审时间"
                    ),
                ),
                (
                    "third_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="三审意见"),
                ),
                (
                    "third_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="三审时间"
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "待一审"),
                            ("first_reviewing", "一审中"),
                            ("first_approved", "一审通过"),
                            ("first_rejected", "一审不通过"),
                            ("second_reviewing", "二审中"),
                            ("second_approved", "二审通过"),
                            ("second_rejected", "二审不通过"),
                            ("third_reviewing", "三审中"),
                            ("approved", "审核通过"),
                            ("rejected", "审核不通过"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("passed", "通过"), ("failed", "不通过")],
                        max_length=10,
                        null=True,
                        verbose_name="结果",
                    ),
                ),
                (
                    "estimated_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        verbose_name="预估分数",
                    ),
                ),
                (
                    "bonus_points",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=7, verbose_name="加分"
                    ),
                ),
                (
                    "college_opinion",
                    models.TextField(blank=True, null=True, verbose_name="学院意见"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "screenshot",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="academic_expertise/%Y/%m/%d/",
                        verbose_name="截图",
                    ),
                ),
                (
                    "user_explanation",
                    models.TextField(blank=True, null=True, verbose_name="用户说明"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paper_title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="论文标题"
                    ),
                ),
                (
                    "journal_category",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="期刊/会议分类",
                    ),
                ),
                (
                    "is_independent_author",
                    models.BooleanField(default=False, verbose_name="是否为独立作者"),
                ),
                (
                    "is_co_first_author",
                    models.BooleanField(default=False, verbose_name="是否为共同一作"),
                ),
                (
                    "author_rank",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="作者排序"
                    ),
                ),
                (
                    "is_xmu_first_unit",
                    models.BooleanField(
                        default=True, verbose_name="厦门大学是否为第一单位"
                    ),
                ),
            ],
            options={
                "verbose_name": "学术论文",
                "verbose_name_plural": "学术论文",
                "db_table": "academic_paper",
            },
        ),
        migrations.CreateModel(
            name="CCFCSPCertification",
            fields=[
                (
                    "first_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="一审意见"),
                ),
                (
                    "first_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="一审时间"
                    ),
                ),
                (
                    "second_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="二审意见"),
                ),
                (
                    "second_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="二审时间"
                    ),
                ),
                (
                    "third_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="三审意见"),
                ),
                (
                    "third_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="三审时间"
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "待一审"),
                            ("first_reviewing", "一审中"),
                            ("first_approved", "一审通过"),
                            ("first_rejected", "一审不通过"),
                            ("second_reviewing", "二审中"),
                            ("second_approved", "二审通过"),
                            ("second_rejected", "二审不通过"),
                            ("third_reviewing", "三审中"),
                            ("approved", "审核通过"),
                            ("rejected", "审核不通过"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("passed", "通过"), ("failed", "不通过")],
                        max_length=10,
                        null=True,
                        verbose_name="结果",
                    ),
                ),
                (
                    "estimated_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        verbose_name="预估分数",
                    ),
                ),
                (
                    "bonus_points",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=7, verbose_name="加分"
                    ),
                ),
                (
                    "college_opinion",
                    models.TextField(blank=True, null=True, verbose_name="学院意见"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "screenshot",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="academic_expertise/%Y/%m/%d/",
                        verbose_name="截图",
                    ),
                ),
                (
                    "user_explanation",
                    models.TextField(blank=True, null=True, verbose_name="用户说明"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.IntegerField(verbose_name="CCF CSP分数")),
                ("certification_date", models.DateField(verbose_name="认证日期")),
                (
                    "csp_rank_percentage",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="排名百分比"
                    ),
                ),
            ],
            options={
                "verbose_name": "CCF CSP认证",
                "verbose_name_plural": "CCF CSP认证",
                "db_table": "ccf_csp_certification",
            },
        ),
        migrations.CreateModel(
            name="EnglishScore",
            fields=[
                (
                    "first_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="一审意见"),
                ),
                (
                    "first_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="一审时间"
                    ),
                ),
                (
                    "second_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="二审意见"),
                ),
                (
                    "second_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="二审时间"
                    ),
                ),
                (
                    "third_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="三审意见"),
                ),
                (
                    "third_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="三审时间"
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "待一审"),
                            ("first_reviewing", "一审中"),
                            ("first_approved", "一审通过"),
                            ("first_rejected", "一审不通过"),
                            ("second_reviewing", "二审中"),
                            ("second_approved", "二审通过"),
                            ("second_rejected", "二审不通过"),
                            ("third_reviewing", "三审中"),
                            ("approved", "审核通过"),
                            ("rejected", "审核不通过"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("passed", "通过"), ("failed", "不通过")],
                        max_length=10,
                        null=True,
                        verbose_name="结果",
                    ),
                ),
                (
                    "estimated_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        verbose_name="预估分数",
                    ),
                ),
                (
                    "bonus_points",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=7, verbose_name="加分"
                    ),
                ),
                (
                    "college_opinion",
                    models.TextField(blank=True, null=True, verbose_name="学院意见"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("cet4", "大学英语四级"), ("cet6", "大学英语六级")],
                        default="cet4",
                        max_length=10,
                        verbose_name="考试类型",
                    ),
                ),
                (
                    "exam_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="请输入具体的分数",
                        max_digits=5,
                        verbose_name="考试成绩",
                    ),
                ),
                (
                    "exam_date",
                    models.DateField(blank=True, null=True, verbose_name="考试日期"),
                ),
                (
                    "score_report",
                    models.FileField(
                        upload_to="english_scores/%Y/%m/%d/", verbose_name="成绩报告单"
                    ),
                ),
                (
                    "meets_standard",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="是否达到标准"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "英语成绩",
                "verbose_name_plural": "英语成绩",
                "db_table": "english_score",
            },
        ),
        migrations.CreateModel(
            name="HonoraryTitle",
            fields=[
                (
                    "first_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="一审意见"),
                ),
                (
                    "first_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="一审时间"
                    ),
                ),
                (
                    "second_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="二审意见"),
                ),
                (
                    "second_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="二审时间"
                    ),
                ),
                (
                    "third_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="三审意见"),
                ),
                (
                    "third_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="三审时间"
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "待一审"),
                            ("first_reviewing", "一审中"),
                            ("first_approved", "一审通过"),
                            ("first_rejected", "一审不通过"),
                            ("second_reviewing", "二审中"),
                            ("second_approved", "二审通过"),
                            ("second_rejected", "二审不通过"),
                            ("third_reviewing", "三审中"),
                            ("approved", "审核通过"),
                            ("rejected", "审核不通过"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("passed", "通过"), ("failed", "不通过")],
                        max_length=10,
                        null=True,
                        verbose_name="结果",
                    ),
                ),
                (
                    "estimated_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        verbose_name="预估分数",
                    ),
                ),
                (
                    "bonus_points",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=7, verbose_name="加分"
                    ),
                ),
                (
                    "college_opinion",
                    models.TextField(blank=True, null=True, verbose_name="学院意见"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("national", "国家级"),
                            ("provincial", "省级"),
                            ("university", "校级"),
                            ("college", "院级"),
                            ("school", "校级"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="级别",
                    ),
                ),
                (
                    "working_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="工时数",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="工作职位"
                    ),
                ),
                (
                    "screenshot",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="comprehensive_performance/%Y/%m/%d/",
                        verbose_name="截图",
                    ),
                ),
                (
                    "user_explanation",
                    models.TextField(blank=True, null=True, verbose_name="用户说明"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="荣誉称号名称",
                    ),
                ),
                (
                    "awarding_organization",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="授予单位"
                    ),
                ),
                (
                    "awarding_date",
                    models.DateField(blank=True, null=True, verbose_name="授予日期"),
                ),
                (
                    "is_collective",
                    models.BooleanField(default=False, verbose_name="是否为集体荣誉"),
                ),
            ],
            options={
                "verbose_name": "荣誉称号",
                "verbose_name_plural": "荣誉称号",
                "db_table": "honorary_title",
            },
        ),
        migrations.CreateModel(
            name="InnovationProject",
            fields=[
                (
                    "first_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="一审意见"),
                ),
                (
                    "first_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="一审时间"
                    ),
                ),
                (
                    "second_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="二审意见"),
                ),
                (
                    "second_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="二审时间"
                    ),
                ),
                (
                    "third_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="三审意见"),
                ),
                (
                    "third_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="三审时间"
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "待一审"),
                            ("first_reviewing", "一审中"),
                            ("first_approved", "一审通过"),
                            ("first_rejected", "一审不通过"),
                            ("second_reviewing", "二审中"),
                            ("second_approved", "二审通过"),
                            ("second_rejected", "二审不通过"),
                            ("third_reviewing", "三审中"),
                            ("approved", "审核通过"),
                            ("rejected", "审核不通过"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("passed", "通过"), ("failed", "不通过")],
                        max_length=10,
                        null=True,
                        verbose_name="结果",
                    ),
                ),
                (
                    "estimated_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        verbose_name="预估分数",
                    ),
                ),
                (
                    "bonus_points",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=7, verbose_name="加分"
                    ),
                ),
                (
                    "college_opinion",
                    models.TextField(blank=True, null=True, verbose_name="学院意见"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "screenshot",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="academic_expertise/%Y/%m/%d/",
                        verbose_name="截图",
                    ),
                ),
                (
                    "user_explanation",
                    models.TextField(blank=True, null=True, verbose_name="用户说明"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project_name",
                    models.CharField(max_length=200, verbose_name="项目名称"),
                ),
                (
                    "project_level",
                    models.CharField(
                        choices=[
                            ("national", "国家级"),
                            ("provincial", "省级"),
                            ("university", "校级"),
                        ],
                        max_length=20,
                        verbose_name="项目级别",
                    ),
                ),
                (
                    "project_duration",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="项目周期"
                    ),
                ),
                (
                    "is_team_leader",
                    models.BooleanField(default=False, verbose_name="是否为项目组长"),
                ),
            ],
            options={
                "verbose_name": "大创项目",
                "verbose_name_plural": "大创项目",
                "db_table": "innovation_project",
            },
        ),
        migrations.CreateModel(
            name="InternationalInternship",
            fields=[
                (
                    "first_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="一审意见"),
                ),
                (
                    "first_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="一审时间"
                    ),
                ),
                (
                    "second_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="二审意见"),
                ),
                (
                    "second_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="二审时间"
                    ),
                ),
                (
                    "third_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="三审意见"),
                ),
                (
                    "third_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="三审时间"
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "待一审"),
                            ("first_reviewing", "一审中"),
                            ("first_approved", "一审通过"),
                            ("first_rejected", "一审不通过"),
                            ("second_reviewing", "二审中"),
                            ("second_approved", "二审通过"),
                            ("second_rejected", "二审不通过"),
                            ("third_reviewing", "三审中"),
                            ("approved", "审核通过"),
                            ("rejected", "审核不通过"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("passed", "通过"), ("failed", "不通过")],
                        max_length=10,
                        null=True,
                        verbose_name="结果",
                    ),
                ),
                (
                    "estimated_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        verbose_name="预估分数",
                    ),
                ),
                (
                    "bonus_points",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=7, verbose_name="加分"
                    ),
                ),
                (
                    "college_opinion",
                    models.TextField(blank=True, null=True, verbose_name="学院意见"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("national", "国家级"),
                            ("provincial", "省级"),
                            ("university", "校级"),
                            ("college", "院级"),
                            ("school", "校级"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="级别",
                    ),
                ),
                (
                    "working_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="工时数",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="工作职位"
                    ),
                ),
                (
                    "screenshot",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="comprehensive_performance/%Y/%m/%d/",
                        verbose_name="截图",
                    ),
                ),
                (
                    "user_explanation",
                    models.TextField(blank=True, null=True, verbose_name="用户说明"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization_name",
                    models.CharField(max_length=200, verbose_name="组织名称"),
                ),
                (
                    "internship_duration",
                    models.CharField(max_length=100, verbose_name="实习时长"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="国家"
                    ),
                ),
            ],
            options={
                "verbose_name": "国际组织实习",
                "verbose_name_plural": "国际组织实习",
                "db_table": "international_internship",
            },
        ),
        migrations.CreateModel(
            name="MilitaryService",
            fields=[
                (
                    "first_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="一审意见"),
                ),
                (
                    "first_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="一审时间"
                    ),
                ),
                (
                    "second_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="二审意见"),
                ),
                (
                    "second_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="二审时间"
                    ),
                ),
                (
                    "third_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="三审意见"),
                ),
                (
                    "third_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="三审时间"
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "待一审"),
                            ("first_reviewing", "一审中"),
                            ("first_approved", "一审通过"),
                            ("first_rejected", "一审不通过"),
                            ("second_reviewing", "二审中"),
                            ("second_approved", "二审通过"),
                            ("second_rejected", "二审不通过"),
                            ("third_reviewing", "三审中"),
                            ("approved", "审核通过"),
                            ("rejected", "审核不通过"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("passed", "通过"), ("failed", "不通过")],
                        max_length=10,
                        null=True,
                        verbose_name="结果",
                    ),
                ),
                (
                    "estimated_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        verbose_name="预估分数",
                    ),
                ),
                (
                    "bonus_points",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=7, verbose_name="加分"
                    ),
                ),
                (
                    "college_opinion",
                    models.TextField(blank=True, null=True, verbose_name="学院意见"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("national", "国家级"),
                            ("provincial", "省级"),
                            ("university", "校级"),
                            ("college", "院级"),
                            ("school", "校级"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="级别",
                    ),
                ),
                (
                    "working_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="工时数",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="工作职位"
                    ),
                ),
                (
                    "screenshot",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="comprehensive_performance/%Y/%m/%d/",
                        verbose_name="截图",
                    ),
                ),
                (
                    "user_explanation",
                    models.TextField(blank=True, null=True, verbose_name="用户说明"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("service_start_date", models.DateField(verbose_name="入伍时间")),
                ("service_end_date", models.DateField(verbose_name="退伍时间")),
                (
                    "military_unit",
                    models.CharField(max_length=200, verbose_name="服役部队"),
                ),
            ],
            options={
                "verbose_name": "参军入伍",
                "verbose_name_plural": "参军入伍",
                "db_table": "military_service",
            },
        ),
        migrations.CreateModel(
            name="PatentWork",
            fields=[
                (
                    "first_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="一审意见"),
                ),
                (
                    "first_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="一审时间"
                    ),
                ),
                (
                    "second_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="二审意见"),
                ),
                (
                    "second_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="二审时间"
                    ),
                ),
                (
                    "third_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="三审意见"),
                ),
                (
                    "third_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="三审时间"
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "待一审"),
                            ("first_reviewing", "一审中"),
                            ("first_approved", "一审通过"),
                            ("first_rejected", "一审不通过"),
                            ("second_reviewing", "二审中"),
                            ("second_approved", "二审通过"),
                            ("second_rejected", "二审不通过"),
                            ("third_reviewing", "三审中"),
                            ("approved", "审核通过"),
                            ("rejected", "审核不通过"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("passed", "通过"), ("failed", "不通过")],
                        max_length=10,
                        null=True,
                        verbose_name="结果",
                    ),
                ),
                (
                    "estimated_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        verbose_name="预估分数",
                    ),
                ),
                (
                    "bonus_points",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=7, verbose_name="加分"
                    ),
                ),
                (
                    "college_opinion",
                    models.TextField(blank=True, null=True, verbose_name="学院意见"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "screenshot",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="academic_expertise/%Y/%m/%d/",
                        verbose_name="截图",
                    ),
                ),
                (
                    "user_explanation",
                    models.TextField(blank=True, null=True, verbose_name="用户说明"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paper_title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="专利名称"
                    ),
                ),
                (
                    "author_type",
                    models.CharField(
                        choices=[
                            ("first_author_except_teacher", "除老师外第一作者"),
                            ("independent_author", "独立作者"),
                        ],
                        default="first_author_except_teacher",
                        max_length=50,
                        verbose_name="作者类型",
                    ),
                ),
                (
                    "is_xmu_first_unit",
                    models.BooleanField(
                        default=True, verbose_name="厦门大学是否为第一单位"
                    ),
                ),
            ],
            options={
                "verbose_name": "专利著作",
                "verbose_name_plural": "专利著作",
                "db_table": "patent_work",
            },
        ),
        migrations.CreateModel(
            name="SocialWork",
            fields=[
                (
                    "first_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="一审意见"),
                ),
                (
                    "first_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="一审时间"
                    ),
                ),
                (
                    "second_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="二审意见"),
                ),
                (
                    "second_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="二审时间"
                    ),
                ),
                (
                    "third_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="三审意见"),
                ),
                (
                    "third_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="三审时间"
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "待一审"),
                            ("first_reviewing", "一审中"),
                            ("first_approved", "一审通过"),
                            ("first_rejected", "一审不通过"),
                            ("second_reviewing", "二审中"),
                            ("second_approved", "二审通过"),
                            ("second_rejected", "二审不通过"),
                            ("third_reviewing", "三审中"),
                            ("approved", "审核通过"),
                            ("rejected", "审核不通过"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("passed", "通过"), ("failed", "不通过")],
                        max_length=10,
                        null=True,
                        verbose_name="结果",
                    ),
                ),
                (
                    "estimated_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        verbose_name="预估分数",
                    ),
                ),
                (
                    "bonus_points",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=7, verbose_name="加分"
                    ),
                ),
                (
                    "college_opinion",
                    models.TextField(blank=True, null=True, verbose_name="学院意见"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("national", "国家级"),
                            ("provincial", "省级"),
                            ("university", "校级"),
                            ("college", "院级"),
                            ("school", "校级"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="级别",
                    ),
                ),
                (
                    "working_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="工时数",
                    ),
                ),
                (
                    "screenshot",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="comprehensive_performance/%Y/%m/%d/",
                        verbose_name="截图",
                    ),
                ),
                (
                    "user_explanation",
                    models.TextField(blank=True, null=True, verbose_name="用户说明"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "position",
                    models.CharField(
                        default="", max_length=100, verbose_name="工作职位"
                    ),
                ),
                (
                    "work_duration",
                    models.CharField(
                        default="", max_length=100, verbose_name="任职时长"
                    ),
                ),
                (
                    "performance_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="工作表现评分",
                    ),
                ),
                (
                    "position_coefficient",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=3,
                        verbose_name="职位系数",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        default="", max_length=200, verbose_name="工作组织"
                    ),
                ),
                (
                    "work_period",
                    models.CharField(
                        default="", max_length=100, verbose_name="工作时间"
                    ),
                ),
                (
                    "work_description",
                    models.TextField(blank=True, null=True, verbose_name="工作描述"),
                ),
            ],
            options={
                "verbose_name": "社会工作",
                "verbose_name_plural": "社会工作",
                "db_table": "social_work",
            },
        ),
        migrations.CreateModel(
            name="SportsCompetition",
            fields=[
                (
                    "first_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="一审意见"),
                ),
                (
                    "first_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="一审时间"
                    ),
                ),
                (
                    "second_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="二审意见"),
                ),
                (
                    "second_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="二审时间"
                    ),
                ),
                (
                    "third_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="三审意见"),
                ),
                (
                    "third_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="三审时间"
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "待一审"),
                            ("first_reviewing", "一审中"),
                            ("first_approved", "一审通过"),
                            ("first_rejected", "一审不通过"),
                            ("second_reviewing", "二审中"),
                            ("second_approved", "二审通过"),
                            ("second_rejected", "二审不通过"),
                            ("third_reviewing", "三审中"),
                            ("approved", "审核通过"),
                            ("rejected", "审核不通过"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("passed", "通过"), ("failed", "不通过")],
                        max_length=10,
                        null=True,
                        verbose_name="结果",
                    ),
                ),
                (
                    "estimated_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        verbose_name="预估分数",
                    ),
                ),
                (
                    "bonus_points",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=7, verbose_name="加分"
                    ),
                ),
                (
                    "college_opinion",
                    models.TextField(blank=True, null=True, verbose_name="学院意见"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("national", "国家级"),
                            ("provincial", "省级"),
                            ("university", "校级"),
                            ("college", "院级"),
                            ("school", "校级"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="级别",
                    ),
                ),
                (
                    "working_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="工时数",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="工作职位"
                    ),
                ),
                (
                    "screenshot",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="comprehensive_performance/%Y/%m/%d/",
                        verbose_name="截图",
                    ),
                ),
                (
                    "user_explanation",
                    models.TextField(blank=True, null=True, verbose_name="用户说明"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition_name",
                    models.CharField(max_length=200, verbose_name="比赛名称"),
                ),
                (
                    "competition_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("international", "国际级"),
                            ("national", "国家级"),
                            ("provincial", "省级"),
                            ("school", "校级"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="竞赛级别",
                    ),
                ),
                (
                    "achievement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("champion", "冠军"),
                            ("runner_up", "亚军"),
                            ("third_place", "季军"),
                            ("fourth_to_eighth", "第四至八名"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="获奖等级",
                    ),
                ),
                (
                    "is_team_project",
                    models.BooleanField(default=False, verbose_name="是否是团队项目"),
                ),
                ("team_size", models.IntegerField(default=1, verbose_name="队伍人数")),
                (
                    "project_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("individual", "单人项目"),
                            ("two_person", "二人项目"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="项目类型",
                    ),
                ),
                (
                    "competition_date",
                    models.DateField(blank=True, null=True, verbose_name="比赛日期"),
                ),
            ],
            options={
                "verbose_name": "体育比赛",
                "verbose_name_plural": "体育比赛",
                "db_table": "sports_competition",
            },
        ),
        migrations.CreateModel(
            name="VolunteerService",
            fields=[
                (
                    "first_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="一审意见"),
                ),
                (
                    "first_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="一审时间"
                    ),
                ),
                (
                    "second_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="二审意见"),
                ),
                (
                    "second_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="二审时间"
                    ),
                ),
                (
                    "third_review_comment",
                    models.TextField(blank=True, null=True, verbose_name="三审意见"),
                ),
                (
                    "third_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="三审时间"
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "待一审"),
                            ("first_reviewing", "一审中"),
                            ("first_approved", "一审通过"),
                            ("first_rejected", "一审不通过"),
                            ("second_reviewing", "二审中"),
                            ("second_approved", "二审通过"),
                            ("second_rejected", "二审不通过"),
                            ("third_reviewing", "三审中"),
                            ("approved", "审核通过"),
                            ("rejected", "审核不通过"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("passed", "通过"), ("failed", "不通过")],
                        max_length=10,
                        null=True,
                        verbose_name="结果",
                    ),
                ),
                (
                    "estimated_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        verbose_name="预估分数",
                    ),
                ),
                (
                    "bonus_points",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=7, verbose_name="加分"
                    ),
                ),
                (
                    "college_opinion",
                    models.TextField(blank=True, null=True, verbose_name="学院意见"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("national", "国家级"),
                            ("provincial", "省级"),
                            ("university", "校级"),
                            ("college", "院级"),
                            ("school", "校级"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="级别",
                    ),
                ),
                (
                    "working_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="工时数",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="工作职位"
                    ),
                ),
                (
                    "screenshot",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="comprehensive_performance/%Y/%m/%d/",
                        verbose_name="截图",
                    ),
                ),
                (
                    "user_explanation",
                    models.TextField(blank=True, null=True, verbose_name="用户说明"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[("hours", "志愿工时"), ("recognition", "志愿表彰")],
                        max_length=20,
                        verbose_name="服务类型",
                    ),
                ),
                (
                    "activity_name",
                    models.CharField(max_length=200, verbose_name="活动名称"),
                ),
                ("activity_date", models.DateField(verbose_name="活动日期")),
                (
                    "award_level",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="表彰级别"
                    ),
                ),
                (
                    "is_team",
                    models.BooleanField(default=False, verbose_name="是否为团队"),
                ),
                (
                    "team_role",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="团队角色"
                    ),
                ),
            ],
            options={
                "verbose_name": "志愿服务",
                "verbose_name_plural": "志愿服务",
                "db_table": "volunteer_service",
            },
        ),
    ]
