# Generated by Django 5.2.6 on 2025-12-26 04:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        decimal_places=4, max_digits=7, verbose_name="学分绩点"
                    ),
                ),
                (
                    "weighted_score",
                    models.DecimalField(
                        decimal_places=4, max_digits=7, verbose_name="加权分数"
                    ),
                ),
                ("total_courses", models.IntegerField(verbose_name="总课程门数")),
                (
                    "total_credits",
                    models.DecimalField(
                        decimal_places=4, max_digits=7, verbose_name="总学分数"
                    ),
                ),
                ("gpa_ranking", models.IntegerField(verbose_name="绩点排名")),
                (
                    "ranking_dimension",
                    models.CharField(max_length=100, verbose_name="排名维度"),
                ),
                (
                    "failed_courses",
                    models.IntegerField(default=0, verbose_name="不及格门数"),
                ),
                (
                    "academic_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        verbose_name="学业成绩(满分80分)",
                    ),
                ),
                (
                    "academic_expertise_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        verbose_name="学术专长成绩(满分15分)",
                    ),
                ),
                (
                    "comprehensive_performance_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        verbose_name="综合表现成绩(满分5分)",
                    ),
                ),
                (
                    "total_comprehensive_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        verbose_name="综合成绩(满分100分)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "学业成绩",
                "verbose_name_plural": "学业成绩",
                "db_table": "academic_performance",
            },
        ),
    ]
