"""
Django settings for xmu_app project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0#tp%cgg$l8w@s+$x9+e%!gs0!%8nkj6vzs7xwef93a@4-%e$e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['testserver', 'localhost', '127.0.0.1']

# 禁用APPEND_SLASH以支持不带斜杠的URL
APPEND_SLASH = False

AUTH_USER_MODEL = 'user.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_yasg',
    'rest_framework_simplejwt',
    'corsheaders',
    'captcha',
    'channels',
    'user',
    'score',
    'material'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # 先执行AuthenticationMiddleware，然后我们的中间件可以覆盖用户对象
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'user.middleware.AccessTokenMiddleware',
    'user.middleware.AccessKeyAuthenticationMiddleware',
    'user.middleware.RateLimitMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 统一错误处理中间件，确保返回JSON格式错误
    'xmu_app.middleware.JSONErrorMiddleware',
]

ROOT_URLCONF = 'xmu_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xmu_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 导入环境变量配置（实际生产环境中应使用环境变量存储敏感信息）
import os
from dotenv import load_dotenv

# 加载环境变量（如果有.env文件）
load_dotenv()

DATABASES = {
    'default': {
        # 使用带连接池的PostgreSQL引擎
        'ENGINE': 'dj_db_conn_pool.backends.postgresql',
        # 数据库名称
        'NAME': os.environ.get('DB_NAME', 'xmudb1.2'),
        # 数据库用户名
        'USER': os.environ.get('DB_USER', 'postgres'),
        # 数据库密码
        'PASSWORD': os.environ.get('DB_PASSWORD', 'Fzh050829'),
        # 数据库主机地址及端口
        'HOST': os.environ.get('DB_HOST', '172.29.197.128'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        # SSL/TLS加密连接配置
        'OPTIONS': {
            # 启用SSL连接
            'sslmode': 'require',
            # 设置查询超时（毫秒）
            'options': '-c statement_timeout=60000',  # 60秒
            # 设置连接超时
            'connect_timeout': 30,
        },
        # 连接池配置
        'POOL_OPTIONS': {
            # 最小空闲连接数
            'min_connections': 5,
            # 最大连接数
            'max_connections': 20,
            # 连接超时时间（秒）
            'connection_timeout': 30,
            # 空闲连接超时时间（秒）
            'idle_timeout': 3600,
            # 最大重试次数
            'max_retries': 3,
        },
    }
}

# 设置事务超时
TRANSACTION_TIMEOUT = 60  # 60秒


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Channels配置
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 认证后端配置
AUTHENTICATION_BACKENDS = [
    'user.authentication.TokenAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'user.authentication.DRFTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # 全局异常处理类，确保DRF错误返回JSON格式
    'EXCEPTION_HANDLER': 'xmu_app.exceptions.custom_exception_handler',
}

# 缓存配置
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 604800,  # 7天，与访问令牌过期时间一致
    }
}

# 文件上传配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 安全配置
SESSION_COOKIE_SECURE = False  # 开发环境设为False，生产环境设为True
CSRF_COOKIE_SECURE = False  # 开发环境设为False，生产环境设为True
SECURE_SSL_REDIRECT = False  # 开发环境设为False，生产环境设为True

# TOTP配置
TOTP_ISSUER_NAME = '学生申请管理系统'
TOTP_DIGITS = 6
TOTP_INTERVAL = 30

# 登录安全配置
MAX_FAILED_LOGIN_ATTEMPTS = 5
ACCOUNT_LOCK_DURATION = 30  # 账户锁定分钟数

# Swagger 配置
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Token': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'DOC_EXPANSION': 'none',
    'APIS_SORTER': 'alpha',
    'OPERATIONS_SORTER': 'alpha',
    'DEFAULT_MODEL_RENDERING': 'example',
}

# Redoc 配置
REDOC_SETTINGS = {
    'LAZY_RENDERING': False,
    'HIDE_HOSTNAME': False,
    'EXPAND_RESPONSES': ['200', '201'],
}

# CORS配置
CORS_ALLOW_ALL_ORIGINS = True  # 开发环境下允许所有来源访问，生产环境建议配置具体域名
CORS_ALLOW_CREDENTIALS = True  # 允许携带认证信息
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS'
]
CORS_ALLOW_HEADERS = [
    'Authorization',
    'Content-Type',
    'X-CSRFToken',
    'X-Requested-With'
]

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'user': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'material': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'xmu_app': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}